batchsize: 20
kernel_size: 5
depth: 4
init_features: 32
stride: 1
dilation: 1
activation_fct: ReLU
norm: batchnorm
repeat_inner: False
skip_per_dir: 16
len_box: 256
train_loss: MSE
bool_cutouts: True
optimizer_switch: False
lr: 0.0001